# Generated by Django 3.2.9 on 2021-11-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_auto_20211107_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='has_orientation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
